using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace IdentityMapping.Infrastructure.Migrations
{
    /// <summary>
    /// This is a placeholder file to indicate where EF Core migrations should be generated.
    /// To create an actual migration, run the following command from the IdentityMapping.IdentityServer project directory:
    /// 
    /// dotnet ef migrations add InitialMigration --project ../IdentityMapping.Infrastructure --startup-project .
    /// dotnet ef database update --project ../IdentityMapping.Infrastructure --startup-project .
    /// </summary>
    public class InitialMigrationPlaceholder
    {
        // This is just a placeholder class to indicate where migrations should go.
        // The actual migrations will be generated by Entity Framework Core.
    }
} 